#!/usr/bin/env python

from subprocess import Popen, PIPE
from optparse import OptionParser

p = OptionParser()
p.add_option('-t', '--title', dest='title', type='str', help='document title')
p.add_option('-a', '--author', dest='author', type='str', help='author')
p.add_option('-v', '--version', dest='version', type='str', help='versio', default='1.0')
(options, args) = p.parse_args()

input='''
y

%s
%s
%s









y






''' % (options.title, options.author, options.version)
proc = Popen(['sphinx-quickstart'], stdin=PIPE, shell=True)
proc.communicate(input)

with open('source/conf.py', 'a') as f:
    f.write('''
# These lines are automatically inserted for Japanese document
language = 'ja'
latex_docclass = {'manual': 'jsbook'}
''')

with open('.gitignore', 'w') as f:
    f.write('''
*~
build
''')
